# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20170119_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='number',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='type',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Phone', verbose_name='Telefono'),
        ),
    ]
