# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('C', 'Casa'), ('M', 'Móvil'), ('T', 'Trabajo')], default='C', max_length=1)),
            ],
        ),
    ]
